# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e2b63115c756ae132348edd6ab46a718d837b18d9320078950d9281253734bd6a50fbf343ec08998279165815b8ffd70fb63dea3a5315ad7ad67716a7068131

test:
  secret_key_base: 1f9a00df0aa3fc0b295de707156c990ff5f9776e6baaf9b25bbcc1349df39bd951f1d8f5930a35bbc569ce52872d6bf4d266b0fe788c566f1229397b6e50aed0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
